---
- name: Standardize SELinux config using .j2
  hosts: all
  vars:
    selinux_mode: enforcing
    selinux_type: targeted

  tasks:
    - name: change template of selinux config file
      template:
        src: selinux.j2
        dest: /etc/selinux/config
      notify: Reboot System
      
  handlers:
    - name: Reboot System
      reboot:

